# 非 host 版本, 不使用本机代理
version: '3.8'
services:
  antskpg:
    image: registry.cn-hangzhou.aliyuncs.com/xuzeyu91/pg:v0.5.0 
    container_name: antskpg
    restart: always
    ports: # 生产环境建议不要暴露
      - 5432:5432
    networks:
      - antsk
    environment:
      # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
      - POSTGRES_USER=sino
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=antsk
    volumes:
      - ./pg/data:/var/lib/postgresql/data
  antsk:
    container_name: antsk
    image: registry.cn-hangzhou.aliyuncs.com/xuzeyu91/antsk:v0.2.9
    # 如果需要pytorch环境需要使用下面这个镜像，镜像比较大
    # image: registry.cn-hangzhou.aliyuncs.com/xuzeyu91/antsk:p0.2.9
    ports:
      - 5000:5000
    networks:
      - antsk
    depends_on:
      - antskpg
    restart: always
    environment:
      - ASPNETCORE_URLS=http://*:5000
    volumes:
      - ./appsettings.json:/app/appsettings.json # 本地配置文件 需要放在同级目录
      - D://model:/app/model
  postgres: # 当前compose服务名
    image: registry.cn-shenzhen.aliyuncs.com/fast-wiki/pgvector:v0.5.0 # 拉取的数据库镜像
    container_name: postgres  # 容器运行的容器名称
    restart: always  # 开机自启动
    ports: # 生产环境建议不要暴露
      - 5432:5432
    environment:  # 环境变量
      POSTGRES_USER: sino  # 默认账号
      POSTGRES_PASSWORD: P@ssw0rd # 默认密码
      POSTGRES_DB: antsk # 默认数据库
      TZ: Asia/Shanghai  # 数据库时区
    volumes:
      - ./postgresql:/var/lib/postgresql/data # 将PostgreSql数据持久化
networks:
  antsk:
